name: Nasazení na Sandbox
on:
  release:
    types:
      - released
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Naklonování repozitáře
        uses: actions/checkout@v4
      - name: Přihlášení se k Sandboxu
        uses: docker/login-action@v3
        with:
          username: ignored
          password: ${{ secrets.SANDBOX_BUILD_TOKEN }}
          registry: registry.pslib.cloud
      - name: Nainstalování Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Sestavení a nahrání kontejnerového obrazu
        uses: docker/build-push-action@v6
        with:
          context: . # změň cestu podle toho, kde se nachází složka s řešením (soubor .sln)
          file: ./Dockerfile # změň cestu podle toho, kde se nachází Dockerfile
          push: true
          tags: registry.pslib.cloud/sandbox/app-108:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
